name: Regular Update
run-name: Updating Calendar
on:
  push:
    branches: ["master"]

  schedule:
    # POSIX cron syntax:
    # https://pubs.opengroup.org/onlinepubs/9699919799/utilities/crontab.html#tag_20_25_07
    - cron: '0 0 * * 0' # 매주 일요일에 실행

# Sets permissions of the GITHUB_TOKEN to allow deployment to GitHub Pages
permissions:
  contents: write

jobs:
  Regular-Update:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: ["3.10"]
    steps:
      - uses: actions/checkout@v3
      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v4
        with:
          python-version: ${{ matrix.python-version }}
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
      - name: Run script
        run: |
          python src/main.py
      - name: Login as github-actions bot
        run: |
          git config user.name 'github-actions[bot]'
          git config user.email 'github-actions[bot]@users.noreply.github.com'
      - name: Apply update to master
        continue-on-error: true
        run: |
          git commit -am "docs: update calendar

          [skip actions]

          Co-authored-by: Hepheir <19310326+Hepheir@users.noreply.github.com>"
          git push origin master